{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"flask_ngrok.ipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"metadata":{"id":"1cljkrUaPeyg","colab":{"base_uri":"https://localhost:8080/"},"outputId":"ae647dfa-cf4b-4fee-95ee-6d8de63a80e8","executionInfo":{"status":"ok","timestamp":1649792819852,"user_tz":-330,"elapsed":36928,"user":{"displayName":"Sagnik Ghosh","userId":"14513161319147678256"}}},"cell_type":"code","source":["!pip install flask-ngrok\n","!pip install flask==0.12.2  \n","!pip install flask-cors\n","!pip install xgboost==1.4.2"],"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting flask-ngrok\n","  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)\n","Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (2.23.0)\n","Requirement already satisfied: Flask>=0.8 in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (1.1.4)\n","Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.0.1)\n","Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (2.11.3)\n","Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.1.0)\n","Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (7.1.2)\n","Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask>=0.8->flask-ngrok) (2.0.1)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2.10)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2021.10.8)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (3.0.4)\n","Installing collected packages: flask-ngrok\n","Successfully installed flask-ngrok-0.0.25\n","Collecting flask==0.12.2\n","  Downloading Flask-0.12.2-py2.py3-none-any.whl (83 kB)\n","\u001b[K     |████████████████████████████████| 83 kB 1.0 MB/s \n","\u001b[?25hRequirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python3.7/dist-packages (from flask==0.12.2) (1.0.1)\n","Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python3.7/dist-packages (from flask==0.12.2) (2.11.3)\n","Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python3.7/dist-packages (from flask==0.12.2) (1.1.0)\n","Requirement already satisfied: click>=2.0 in /usr/local/lib/python3.7/dist-packages (from flask==0.12.2) (7.1.2)\n","Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2>=2.4->flask==0.12.2) (2.0.1)\n","Installing collected packages: flask\n","  Attempting uninstall: flask\n","    Found existing installation: Flask 1.1.4\n","    Uninstalling Flask-1.1.4:\n","      Successfully uninstalled Flask-1.1.4\n","Successfully installed flask-0.12.2\n","Collecting flask-cors\n","  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)\n","Requirement already satisfied: Flask>=0.9 in /usr/local/lib/python3.7/dist-packages (from flask-cors) (0.12.2)\n","Requirement already satisfied: Six in /usr/local/lib/python3.7/dist-packages (from flask-cors) (1.15.0)\n","Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.9->flask-cors) (1.1.0)\n","Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.9->flask-cors) (2.11.3)\n","Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.9->flask-cors) (1.0.1)\n","Requirement already satisfied: click>=2.0 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.9->flask-cors) (7.1.2)\n","Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2>=2.4->Flask>=0.9->flask-cors) (2.0.1)\n","Installing collected packages: flask-cors\n","Successfully installed flask-cors-3.0.10\n","Collecting xgboost==1.4.2\n","  Downloading xgboost-1.4.2-py3-none-manylinux2010_x86_64.whl (166.7 MB)\n","\u001b[K     |████████████████████████████████| 166.7 MB 15 kB/s \n","\u001b[?25hRequirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost==1.4.2) (1.4.1)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from xgboost==1.4.2) (1.21.5)\n","Installing collected packages: xgboost\n","  Attempting uninstall: xgboost\n","    Found existing installation: xgboost 0.90\n","    Uninstalling xgboost-0.90:\n","      Successfully uninstalled xgboost-0.90\n","Successfully installed xgboost-1.4.2\n"]}]},{"cell_type":"code","source":["!curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo \"deb https://ngrok-agent.s3.amazonaws.com buster main\" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok   "],"metadata":{"id":"dZPQOGWgXIgn","outputId":"7ad6a774-28c2-414e-b849-a116622cd3d3","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1649792837862,"user_tz":-330,"elapsed":18056,"user":{"displayName":"Sagnik Ghosh","userId":"14513161319147678256"}}},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["deb https://ngrok-agent.s3.amazonaws.com buster main\n","Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]\n","Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease\n","Get:3 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,622 B]\n","Get:4 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]\n","Ign:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease\n","Hit:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release\n","Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease\n","Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release\n","Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]\n","Get:10 https://ngrok-agent.s3.amazonaws.com buster InRelease [7,470 B]\n","Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,490 kB]\n","Hit:12 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease\n","Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,694 kB]\n","Get:14 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease [15.9 kB]\n","Get:15 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]\n","Hit:17 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease\n","Get:19 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [1,947 kB]\n","Get:20 https://ngrok-agent.s3.amazonaws.com buster/main amd64 Packages [771 B]\n","Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,133 kB]\n","Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,268 kB]\n","Get:23 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main amd64 Packages [996 kB]\n","Get:24 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic/main amd64 Packages [45.3 kB]\n","Fetched 12.9 MB in 3s (3,995 kB/s)\n","Reading package lists... Done\n","Building dependency tree       \n","Reading state information... Done\n","40 packages can be upgraded. Run 'apt list --upgradable' to see them.\n","Reading package lists... Done\n","Building dependency tree       \n","Reading state information... Done\n","The following NEW packages will be installed:\n","  ngrok\n","0 upgraded, 1 newly installed, 0 to remove and 40 not upgraded.\n","Need to get 5,444 kB of archives.\n","After this operation, 0 B of additional disk space will be used.\n","Get:1 https://ngrok-agent.s3.amazonaws.com buster/main amd64 ngrok amd64 3.0.2 [5,444 kB]\n","Fetched 5,444 kB in 1s (4,739 kB/s)\n","debconf: unable to initialize frontend: Dialog\n","debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)\n","debconf: falling back to frontend: Readline\n","debconf: unable to initialize frontend: Readline\n","debconf: (This frontend requires a controlling tty.)\n","debconf: falling back to frontend: Teletype\n","dpkg-preconfigure: unable to re-open stdin: \n","Selecting previously unselected package ngrok.\n","(Reading database ... 155455 files and directories currently installed.)\n","Preparing to unpack .../archives/ngrok_3.0.2_amd64.deb ...\n","Unpacking ngrok (3.0.2) ...\n","Setting up ngrok (3.0.2) ...\n"]}]},{"cell_type":"code","source":["!ngrok authtoken "],"metadata":{"id":"LpbN8IQeXL-w","outputId":"8486a619-eb56-4d78-e92e-2af1b8361f0a","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1649792837865,"user_tz":-330,"elapsed":48,"user":{"displayName":"Sagnik Ghosh","userId":"14513161319147678256"}}},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["NAME:\n","  authtoken - \n","\n","USAGE:\n","  ngrok authtoken TOKEN [flags]\n","\n","DESCRIPTION: \n","\n","OPTIONS:\n","      --config string       save in this config file (default /root/.config/ngrok/ngrok.yml)\n","  -h, --help                help for authtoken\n","      --log string          path to log file, 'stdout', 'stderr' or 'false' (default \"false\")\n","      --log-format string   log record format: 'term', 'logfmt', 'json' (default \"term\")\n","      --log-level string    logging level: 'debug', 'info', 'warn', 'error', 'crit' (default \"info\")\n","\n","ERROR:  accepts 1 arg(s), received 0\n"]}]},{"cell_type":"code","source":["from flask_ngrok import run_with_ngrok\n","from flask import Flask, render_template, request, redirect, url_for, flash, jsonify\n","from flask_cors import CORS, cross_origin\n","import pandas as pd\n","import xgboost as xgb\n","import pickle\n","import numpy as np\n","\n","# __________________________________________________________________________\n","class EncoderExt(object):\n","    def __init__(self):\n","        self.label_encoder = LabelEncoder()\n","     \n","    def fit(self, data_list):\n","        self.label_encoder = self.label_encoder.fit(list(data_list) + ['Unknown'])\n","        self.classes_ = self.label_encoder.classes_\n","        return self\n","\n","    def transform(self, data_list):\n","        new_data_list = list(data_list)\n","        for unique_item in np.unique(data_list):\n","            if unique_item not in self.label_encoder.classes_:\n","                new_data_list = ['Unknown' if x == unique_item else x for x in new_data_list]\n","        return self.label_encoder.transform(new_data_list)\n","# __________________________________________________________________________\n","\n","\n","\n","pickle_files = pickle.load(open(\"pickle_save_files.pkl\", \"rb\"))\n","name_encoder, business_ecoder, cust_payment_terms_encoder, model = pickle_files\n","\n","cols = ['cust_number', 'buisness_year', 'doc_id', 'converted_usd','business_code_enc', 'name_customer_enc', \n","        'cust_payment_terms_enc','day_of_postingdate', 'month_of_postingdate', 'year_of_postingdate',\n","        'day_of_createdate', 'month_of_createdate', 'year_of_createdate', 'day_of_due', 'month_of_due', 'year_of_due']\n","\n","\n","\n","def add_missing(row):\n","    temp = row\n","    temp[\"buisness_year\"] = row[\"business_year\"]\n","    if temp[\"invoice_currency\"] == \"CAD\":\n","        temp[\"converted_usd\"] = row[\"total_open_amount\"]*0.7\n","    else:\n","         temp[\"converted_usd\"] = row[\"total_open_amount\"] \n","    temp[\"day_of_postingdate\"] = row[\"posting_date\"][\"day\"]\n","    temp[\"month_of_postingdate\"] = row[\"posting_date\"][\"month\"]\n","    temp[\"year_of_postingdate\"] = row[\"posting_date\"][\"year\"]\n","    \n","    temp[\"day_of_createdate\"] = row[\"document_create_date\"][\"day\"]\n","    temp[\"month_of_createdate\"] = row[\"document_create_date\"][\"month\"]\n","    temp[\"year_of_createdate\"] = row[\"document_create_date\"][\"year\"]\n","    \n","    temp[\"day_of_due\"] = row[\"due_in_date\"][\"day\"]\n","    temp[\"month_of_due\"] = row[\"due_in_date\"][\"month\"]\n","    temp[\"year_of_due\"] = row[\"due_in_date\"][\"year\"]\n","   \n","    return temp\n","\n","\n","def return_df(rows):\n","    for row in rows:\n","        row = add_missing(row)\n","    df = pd.DataFrame(rows)\n","    df['cust_payment_terms_enc'] = cust_payment_terms_encoder.transform(df['cust_payment_terms'])\n","    df['business_code_enc'] = business_ecoder.transform(df['business_code'])\n","    df['name_customer_enc'] = name_encoder.transform(df['name_customer'])\n","    df = df[cols]\n","    return df\n","\n","def return_predicted_date(due_in_date, delay_seconds):\n","    due_in_date = \"{}-{}-{}\".format(due_in_date[\"year\"], due_in_date[\"month\"], due_in_date[\"day\"])\n","    due_in_date = pd.to_datetime(due_in_date)\n","    predicted_date = due_in_date + pd.Timedelta(seconds=delay_seconds)\n","    return predicted_date.strftime(\"%Y-%m-%d\")\n","\n","def funct(data):\n","    data_list = []\n","    json_df = return_df(data)\n","    result =  model.predict(json_df)\n","    for i in range(len(data)):\n","        temp = {}\n","        temp[\"sl_no\"] = data[i][\"id\"]\n","        temp[\"predicted_payment_date\"] = return_predicted_date(data[i][\"due_in_date\"], result[i])\n","        data_list.append(temp)\n","    return data_list\n","    \n","\n","\n","app = Flask(__name__)\n","app.config['JSONIFY_PRETTYPRINT_REGULAR'] = False\n","run_with_ngrok(app) \n","CORS(app, support_credentials=True)\n","\n","@app.route('/predict', methods=['POST','GET'])\n","def predict():\n","    data = funct(request.json)\n","    print(data)\n","    \n","    return jsonify(data)\n","\n","\n","@app.route('/')\n","def home():\n","    return render_template('index.html')\n","\n","\n","if __name__ == '__main__':\n","    app.run()\n","\n"],"metadata":{"id":"OK8S8vooXuK_","outputId":"7e2dca88-4e0e-4467-a528-965c60240a19","colab":{"base_uri":"https://localhost:8080/"}},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.7/dist-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.24.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\n","https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations\n","  UserWarning,\n"," * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n"]},{"output_type":"stream","name":"stdout","text":[" * Running on http://313a-35-229-106-226.ngrok.io\n"," * Traffic stats available on http://127.0.0.1:4040\n"]},{"output_type":"stream","name":"stderr","text":["[2022-04-12 19:47:53,983] ERROR in app: Exception on / [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 104, in home\n","    return render_template('index.html')\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 133, in render_template\n","    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 930, in get_or_select_template\n","    return self.get_template(template_name_or_list, parent, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 883, in get_template\n","    return self._load_template(name, self.make_globals(globals))\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 857, in _load_template\n","    template = self.loader.load(self, name, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/loaders.py\", line 115, in load\n","    source, filename, uptodate = self.get_source(environment, name)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 57, in get_source\n","    return self._get_source_fast(environment, template)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 85, in _get_source_fast\n","    raise TemplateNotFound(template)\n","jinja2.exceptions.TemplateNotFound: index.html\n","127.0.0.1 - - [12/Apr/2022 19:47:53] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:48:12,324] ERROR in app: Exception on / [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 104, in home\n","    return render_template('index.html')\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 133, in render_template\n","    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 930, in get_or_select_template\n","    return self.get_template(template_name_or_list, parent, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 883, in get_template\n","    return self._load_template(name, self.make_globals(globals))\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 857, in _load_template\n","    template = self.loader.load(self, name, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/loaders.py\", line 115, in load\n","    source, filename, uptodate = self.get_source(environment, name)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 57, in get_source\n","    return self._get_source_fast(environment, template)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 85, in _get_source_fast\n","    raise TemplateNotFound(template)\n","jinja2.exceptions.TemplateNotFound: index.html\n","127.0.0.1 - - [12/Apr/2022 19:48:12] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:48:21,664] ERROR in app: Exception on / [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 104, in home\n","    return render_template('index.html')\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 133, in render_template\n","    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 930, in get_or_select_template\n","    return self.get_template(template_name_or_list, parent, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 883, in get_template\n","    return self._load_template(name, self.make_globals(globals))\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 857, in _load_template\n","    template = self.loader.load(self, name, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/loaders.py\", line 115, in load\n","    source, filename, uptodate = self.get_source(environment, name)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 57, in get_source\n","    return self._get_source_fast(environment, template)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 85, in _get_source_fast\n","    raise TemplateNotFound(template)\n","jinja2.exceptions.TemplateNotFound: index.html\n","127.0.0.1 - - [12/Apr/2022 19:48:21] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n","127.0.0.1 - - [12/Apr/2022 19:48:22] \"\u001b[33mGET /robots.txt HTTP/1.1\u001b[0m\" 404 -\n","[2022-04-12 19:48:23,863] ERROR in app: Exception on / [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 104, in home\n","    return render_template('index.html')\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 133, in render_template\n","    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 930, in get_or_select_template\n","    return self.get_template(template_name_or_list, parent, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 883, in get_template\n","    return self._load_template(name, self.make_globals(globals))\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 857, in _load_template\n","    template = self.loader.load(self, name, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/loaders.py\", line 115, in load\n","    source, filename, uptodate = self.get_source(environment, name)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 57, in get_source\n","    return self._get_source_fast(environment, template)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 85, in _get_source_fast\n","    raise TemplateNotFound(template)\n","jinja2.exceptions.TemplateNotFound: index.html\n","127.0.0.1 - - [12/Apr/2022 19:48:23] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:48:37,464] ERROR in app: Exception on / [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 104, in home\n","    return render_template('index.html')\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 133, in render_template\n","    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 930, in get_or_select_template\n","    return self.get_template(template_name_or_list, parent, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 883, in get_template\n","    return self._load_template(name, self.make_globals(globals))\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 857, in _load_template\n","    template = self.loader.load(self, name, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/loaders.py\", line 115, in load\n","    source, filename, uptodate = self.get_source(environment, name)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 57, in get_source\n","    return self._get_source_fast(environment, template)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 85, in _get_source_fast\n","    raise TemplateNotFound(template)\n","jinja2.exceptions.TemplateNotFound: index.html\n","127.0.0.1 - - [12/Apr/2022 19:48:37] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n","127.0.0.1 - - [12/Apr/2022 19:48:38] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n","[2022-04-12 19:51:38,128] ERROR in app: Exception on / [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 104, in home\n","    return render_template('index.html')\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 133, in render_template\n","    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 930, in get_or_select_template\n","    return self.get_template(template_name_or_list, parent, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 883, in get_template\n","    return self._load_template(name, self.make_globals(globals))\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/environment.py\", line 857, in _load_template\n","    template = self.loader.load(self, name, globals)\n","  File \"/usr/local/lib/python3.7/dist-packages/jinja2/loaders.py\", line 115, in load\n","    source, filename, uptodate = self.get_source(environment, name)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 57, in get_source\n","    return self._get_source_fast(environment, template)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/templating.py\", line 85, in _get_source_fast\n","    raise TemplateNotFound(template)\n","jinja2.exceptions.TemplateNotFound: index.html\n","127.0.0.1 - - [12/Apr/2022 19:51:38] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n","127.0.0.1 - - [12/Apr/2022 19:52:15] \"\u001b[33mGET /predtion HTTP/1.1\u001b[0m\" 404 -\n","127.0.0.1 - - [12/Apr/2022 19:52:22] \"\u001b[33mGET /predct HTTP/1.1\u001b[0m\" 404 -\n","[2022-04-12 19:52:29,162] ERROR in app: Exception on /predict [GET]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 78, in funct\n","    json_df = return_df(data)\n","  File \"<ipython-input-4-48da77e97c48>\", line 61, in return_df\n","    for row in rows:\n","TypeError: 'NoneType' object is not iterable\n","127.0.0.1 - - [12/Apr/2022 19:52:29] \"\u001b[35m\u001b[1mGET /predict HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:53:52,343] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 82, in funct\n","    temp[\"sl_no\"] = data[i][\"id\"]\n","KeyError: 'id'\n","127.0.0.1 - - [12/Apr/2022 19:53:52] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:56:22,549] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 82, in funct\n","    temp[\"sl_no\"] = data[i][\"id\"]\n","KeyError: 'id'\n","127.0.0.1 - - [12/Apr/2022 19:56:22] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:57:10,605] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 78, in funct\n","    json_df = return_df(data)\n","  File \"<ipython-input-4-48da77e97c48>\", line 61, in return_df\n","    for row in rows:\n","TypeError: 'NoneType' object is not iterable\n","127.0.0.1 - - [12/Apr/2022 19:57:10] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:57:18,279] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 78, in funct\n","    json_df = return_df(data)\n","  File \"<ipython-input-4-48da77e97c48>\", line 61, in return_df\n","    for row in rows:\n","TypeError: 'NoneType' object is not iterable\n","127.0.0.1 - - [12/Apr/2022 19:57:18] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:57:19,529] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 78, in funct\n","    json_df = return_df(data)\n","  File \"<ipython-input-4-48da77e97c48>\", line 61, in return_df\n","    for row in rows:\n","TypeError: 'NoneType' object is not iterable\n","127.0.0.1 - - [12/Apr/2022 19:57:19] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n","[2022-04-12 19:57:25,261] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 78, in funct\n","    json_df = return_df(data)\n","  File \"<ipython-input-4-48da77e97c48>\", line 61, in return_df\n","    for row in rows:\n","TypeError: 'NoneType' object is not iterable\n","127.0.0.1 - - [12/Apr/2022 19:57:25] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n","127.0.0.1 - - [12/Apr/2022 19:57:30] \"\u001b[31m\u001b[1mPOST / HTTP/1.1\u001b[0m\" 405 -\n","[2022-04-12 19:57:35,317] ERROR in app: Exception on /predict [POST]\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n","    response = self.full_dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n","    rv = self.handle_user_exception(e)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py\", line 165, in wrapped_function\n","    return cors_after_request(app.make_response(f(*args, **kwargs)))\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n","    reraise(exc_type, exc_value, tb)\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 33, in reraise\n","    raise value\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n","    rv = self.dispatch_request()\n","  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n","    return self.view_functions[rule.endpoint](**req.view_args)\n","  File \"<ipython-input-4-48da77e97c48>\", line 96, in predict\n","    data = funct(request.json)\n","  File \"<ipython-input-4-48da77e97c48>\", line 78, in funct\n","    json_df = return_df(data)\n","  File \"<ipython-input-4-48da77e97c48>\", line 61, in return_df\n","    for row in rows:\n","TypeError: 'NoneType' object is not iterable\n","127.0.0.1 - - [12/Apr/2022 19:57:35] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n"]}]}]}